language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: "IasXoCFWQ25TporMRkyF+f7T52ObnsN897nhII3N8+z20KRejsPU4zjLY7ul8O/+dTxKC9VzatN1AhFFRwGf7GVmfxwxd+QfMqt2is7TvlVq05wGCmdVym/5705wrBpFoCxLnl4OLndQlUNyXtbPQ52fZwYuQUMU9Q3NSdKmXbwgQ1S7gLP2mFhsid6/UtR2IRjsJGOhFNt8yXX7QlhJ+iXb4IxSIEzCJk6oeSd88Q5JhcSBIYRFKqiO/i2fGHfhvI5/vk4OuDqFxgYvxblgGX2xZ4pwQCWPjw66P2fpB4cb2V+6S1z8ia1a/TBW44ZaUDMt4a6YQaN2cORKSYozQxOaAbFRb9xkg+1ptL0k/PlHSBSwsRV0TukfYMM9yq80x43ReMB0oT6uDj/0A9TOXW11/rPHYZBpk5dE8rNI4ldpewJ7e1O/9QoQXFRHUzjYroORKwoDaCTBPrZ8VMDY8RvhqjOt2TLm6fNZt2Ek14Qv9NoRjcygegNsJ98yTBVqjbhT0Yg3CqCedBU19PUoSD2A98TplANxKvyuKquGddFIWZh6/k8ucSSjSOF8qc/8utO0iLLJh+AgGYMyUX5jKR1mj7XYV73GqKsQq/ngs6ivS69CfUu/Flfb0pNSkPkFgI/HBsXC8NFJLelIHmlQvthBtvK0cHa2xuJc2HN508A="
  app: whispering-plains-97815
  on:
    repo: sobhit000/VideoConferenceApp
