language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: HjWPcLOTfWzRhcUWV68kr1zA8+q3Op4ALgdg8jhRlhCjTqmwhGFZ6Sro0EKWZZ9yOlv6UqPY9T9iBVOai0WsVBu8wUhjA3TL6izIU0tu+gw3lusv4e5/fkbBjBWhKpGQfQ/qum0nSRFH/dBg/Cov60lM67zbj1veQuOiX00bZQ5kApK+yOWvAs9OA+Z2viMwshvM1Q666bRdUz8+AtpGTvoHcBiWWdsXQg8xIDagd4D/fO9XAimbeUO6otpGT1qdYmigqdCh9f+MdDSF1A6FkmDFVs6/q0x0Rqc+5FDmSNYWcAPSq+PeTWnpllUBC57GmNldyCJ+r8PS7+HBmAQgGjVoF9Bk7G8oGuwAAj1biNktfS6hUQTXTatE9X8Oy246Ejg41WLfQ5cdqwJyiY9owyHdlvR4V0q3/NdXAj2btD+3tOZnQhvBksA5rqYCXPDCIDAABfmYkE99ocsaxspejFPdUaJTKgVo0HNvCRa6UxShAfUAOL/VRLcODw1Fu2EarbA2Se+Loue8O2C6PabyVLOKlYdbwQKqbehV/FDo6Ao2QJuTaXHRWfbBZSCQ8rp9AwjJWVe9waaf3vYWVZC2wMApq0ZkmLGkIVZaAo5c3EJXuriYlKljMp7DbRRQ6LzyS5MGgvWDe104nfwQ0AS0Os1Gwl/5bNQ7mwZmnbSIsYg=
  app: shielded-refuge-12137
  on:
    repo: sobhit000/VideoConferenceApp
